* tasks

** claudebox.sh:: let user supply a name via --name.

** put the .sh files in a bin/ dir so I can put them on PATH; remove .sh suffix.

** move the files copied into image into their own dir
Dockerfile COPY-s some files into image:

    CLAUDE-TEMPLATE.md          ->  ~/.claude/CLAUDE.md
    gitconfig                   ->  ~/.gitconfig
    claude-settings-json.json   ->  ~/.claude/settings.json

put these into their own directory. if that dir structure mirrors the intended layout in
image, can I use just one COPY instead of one per file?

* future ideas

** consider converting claudebox.sh to python if it gets more complex

** container lifetime defaults

now: claudebox.sh runs a long-lived container.
alternatives:

- `container run --rm` so it's transient.

- `container start` so it doesn't sleep when I leave the session. I often find myself
  "exec bash"-ing in to the container. If I unexpectedly ctrl-D out of the `container run`
  session, the container stops and I lose state.

- cache/reuse containers according to the working directory.

** github permissions convenience

would be nice to have a better way to grant tightly scoped github permissions than manually generating PATs.
- make a GH app?
- other options?
